name = "sudoku"
uuid = "44dbd050-dabe-4a29-9887-d864d33dd3b3"
authors = ["Andrew <andrew.hale003@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]